name: SecureBan
author: Pie
version: "1.0PieAlpha"
api: [1.12.0]
main: Pie\Main
commands:
    uuidban:
        description: "Secures a ban by banning its UUID!"
        usage: "/uuidban"
        permission: uuidban.command
